language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - bin/.phpunit

php:
    - 7.2

before_install:
    - composer self-update

install:
    - composer install --no-scripts --no-interaction

script:
    - bin/phpunit
